apiVersion: v1
kind: ServiceAccount
metadata:
  name: market
  namespace: market
  annotations:
    # AWS IRSA — IAM Role for ServiceAccount
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/market-app
